#ifndef BUILTINS_H_
#define BUILTINS_H_
#include <string>

#include "fuzz_target.h"

namespace builtins {

#if DRY_RUN == 1

const std::string variables[] = {};
const std::string functions[] = {};
const std::string methods[] = {};

#endif  // if DRY_RUN

#if FUZZ_CHAKRA == 1
const std::string variables[] = {
    "NaN",         "undefined",   "Reflect",     "Math",      "JSON",
    "Intl",        "WebAssembly", "WScript",     "console",   "variables",
    "functions",   "methods",     "top",         "__proto__", "E",
    "LN10",        "LN2",         "LOG2E",       "LOG10E",    "PI",
    "SQRT1_2",     "SQRT2",       "Platform",    "Arguments", "ARCH",
    "BUILD_TYPE",  "LINK_TYPE",   "BINARY_PATH", "OS",        "INTL_LIBRARY",
    "ICU_VERSION", "length",      "size"};

const std::string functions[] = {"eval",
                                 "parseInt",
                                 "parseFloat",
                                 "isNaN",
                                 "isFinite",
                                 "decodeURI",
                                 "decodeURIComponent",
                                 "encodeURI",
                                 "encodeURIComponent",
                                 "escape",
                                 "unescape",
                                 "Object",
                                 "Array",
                                 "Boolean",
                                 "Symbol",
                                 "Proxy",
                                 "Promise",
                                 "Date",
                                 "Function",
                                 "Number",
                                 "String",
                                 "RegExp",
                                 "ArrayBuffer",
                                 "DataView",
                                 "Int8Array",
                                 "Uint8Array",
                                 "Uint8ClampedArray",
                                 "Int16Array",
                                 "Uint16Array",
                                 "Int32Array",
                                 "Uint32Array",
                                 "Float32Array",
                                 "Float64Array",
                                 "Map",
                                 "Set",
                                 "WeakMap",
                                 "WeakSet",
                                 "Error",
                                 "EvalError",
                                 "RangeError",
                                 "ReferenceError",
                                 "SyntaxError",
                                 "TypeError",
                                 "URIError",
                                 "print",
                                 "read",
                                 "readbuffer",
                                 "readline",
                                 "extractBuiltins"};

const std::string methods[] = {"defineProperty",
                               "deleteProperty",
                               "get",
                               "getOwnPropertyDescriptor",
                               "getPrototypeOf",
                               "has",
                               "isExtensible",
                               "ownKeys",
                               "preventExtensions",
                               "set",
                               "setPrototypeOf",
                               "apply",
                               "construct",
                               "constructor",
                               "hasOwnProperty",
                               "propertyIsEnumerable",
                               "isPrototypeOf",
                               "toLocaleString",
                               "toString",
                               "valueOf",
                               "__defineGetter__",
                               "__defineSetter__",
                               "__lookupGetter__",
                               "__lookupSetter__",
                               "abs",
                               "acos",
                               "asin",
                               "atan",
                               "atan2",
                               "cos",
                               "ceil",
                               "exp",
                               "floor",
                               "log",
                               "pow",
                               "random",
                               "round",
                               "sin",
                               "sqrt",
                               "tan",
                               "imul",
                               "fround",
                               "log10",
                               "log2",
                               "log1p",
                               "expm1",
                               "cosh",
                               "sinh",
                               "tanh",
                               "acosh",
                               "asinh",
                               "atanh",
                               "hypot",
                               "trunc",
                               "sign",
                               "cbrt",
                               "clz32",
                               "min",
                               "max",
                               "stringify",
                               "parse",
                               "getCanonicalLocales",
                               "Collator",
                               "NumberFormat",
                               "DateTimeFormat",
                               "PluralRules",
                               "compile",
                               "compileStreaming",
                               "validate",
                               "instantiate",
                               "instantiateStreaming",
                               "Module",
                               "Instance",
                               "CompileError",
                               "RuntimeError",
                               "LinkError",
                               "Memory",
                               "Table",
                               "Echo",
                               "Quit",
                               "LoadScriptFile",
                               "LoadScript",
                               "LoadModule",
                               "SetTimeout",
                               "ClearTimeout",
                               "Attach",
                               "Detach",
                               "DumpFunctionPosition",
                               "RequestAsyncBreak",
                               "LoadBinaryFile",
                               "LoadTextFile",
                               "Flag",
                               "RegisterModuleSource",
                               "GetModuleNamespace",
                               "GetProxyProperties",
                               "Edit",
                               "push",
                               "concat",
                               "join",
                               "pop",
                               "reverse",
                               "shift",
                               "slice",
                               "splice",
                               "unshift",
                               "lastIndexOf",
                               "map",
                               "reduceRight",
                               "find",
                               "findIndex",
                               "fill",
                               "copyWithin",
                               "keys",
                               "values",
                               "entries",
                               "indexOf",
                               "sort",
                               "filter",
                               "flat",
                               "flatMap",
                               "forEach",
                               "some",
                               "every",
                               "includes",
                               "reduce",
                               "add",
                               "clear",
                               "delete"};
#endif  // if FUZZ_CHAKRA == 1

#if FUZZ_JERRY == 1
const std::string variables[] = {"this", "bytelength", "byteOffset", "buffer",
                                 "arguments"};

const std::string functions[] = {"assert",
                                 "gc",
                                 "print",
                                 "unescape",
                                 "escape",
                                 "parseInt",
                                 "encodeURIComponent",
                                 "encodeURI",
                                 "decodeURIComponent",
                                 "decodeURI",
                                 "isFinite",
                                 "isNaN",
                                 "parseFloat",
                                 "eval",
                                 "Error",
                                 "Object",
                                 "Promise",
                                 "Number",
                                 "String",
                                 "Array",
                                 "Function",
                                 "JSON",
                                 "Math",
                                 "delete",
                                 "Date",
                                 "typeof",
                                 "RangeError",
                                 "throw",
                                 "ReferenceError",
                                 "Error",
                                 "EvalError",
                                 "TypeError"};

const std::string methods[] = {
    // Warning: this list is autogenerated.
    "getPrototypeOf",
    "subarray",
    "set",
    "from",
    "stringify",
    "test",
    "exec",
    "compile",
    "constructor",
    "this.RegExp",
    "toGMTString",
    "setYear",
    "getYear",
    "toJSON",
    "toISOString",
    "toUTCString",
    "setUTCFullYear",
    "setFullYear",
    "setUTCMonth",
    "setMonth",
    "setUTCDate",
    "setDate",
    "setUTCHours",
    "setHours",
    "setUTCMinutes",
    "setMinutes",
    "setUTCSeconds",
    "setSeconds",
    "setUTCMilliseconds",
    "setMilliseconds",
    "setTime",
    "getTimezoneOffset",
    "getUTCMilliseconds",
    "getMilliseconds",
    "getUTCSeconds",
    "getSeconds",
    "getUTCMinutes",
    "getMinutes",
    "getUTCHours",
    "getHours",
    "getUTCDay",
    "getDay",
    "getUTCDate",
    "getDate",
    "getUTCMonth",
    "getMonth",
    "getUTCFullYear",
    "getFullYear",
    "getTime",
    "valueOf",
    "toLocaleTimeString",
    "toLocaleDateString",
    "toLocaleString",
    "toTimeString",
    "toDateString",
    "toString",
    "toPrecision",
    "toExponential",
    "fill",
    "toFixed",
    "substr",
    "trim",
    "toLocaleUpperCase",
    "toUpperCase",
    "toLocaleLowerCase",
    "toLowerCase",
    "substring",
    "split",
    "search",
    "replace",
    "match",
    "localeCompare",
    "charCodeAt",
    "charAt",
    "lastIndexOf",
    "indexOf",
    "slice",
    "concat",
    "valueOf",
    "reduceRight",
    "reduce",
    "filter",
    "map",
    "forEach",
    "some",
    "every",
    "lastIndexOf",
    "indexOf",
    "unshift",
    "splice",
    "sort",
    "slice",
    "shift",
    "reverse",
    "push",
    "pop",
    "join",
    "concat",
    "bind",
    "call",
    "apply",
    "constructor",
    "propertyIsEnumerable",
    "isPrototypeOf",
    "hasOwnProperty",
    "valueOf",
    "constructor",
    "parse",
    "ceil",
    "tan",
    "sqrt",
    "sin",
    "round",
    "random",
    "pow",
    "min",
    "max",
    "log",
    "floor",
    "exp",
    "cos",
    "atan2",
    "atan",
    "asin",
    "acos",
    "abs",
    "now",
    "UTC",
    "then",
};
#endif  // if FUZZ_JERRY == 1

#if FUZZ_ESPURINO == 1
const std::string variables[] = {
    "this", "bytelength", "byteOffset", "buffer", "arguments", "__proto__",
    "D0",   "D1",         "D2",         "D3",     "D4",        "D5",
    "D6",   "D7",         "D8",         "D9",     "D10",       "D11",
    "D12",  "D13",        "D14",        "D15",    "D16",       "D17",
    "D18",  "D19",        "D20",        "D21",    "D22",       "D23",
    "D24",  "D25",        "D26",        "D27",    "D28",       "D29",
    "D30",  "D31",        "D32"};

const std::string functions[] = {"quit",
                                 "interrupt",
                                 "Object",
                                 "console",
                                 "x",
                                 "AES",
                                 "Array",
                                 "ArrayBuffer",
                                 "ArrayBufferView",
                                 "Boolean",
                                 "DataView",
                                 "Date",
                                 "E",
                                 "Error",
                                 "File",
                                 "Float32Array",
                                 "Float64Array",
                                 "Function",
                                 "Graphics",
                                 "HASH",
                                 "HIGH",
                                 "I2C",
                                 "I2C1",
                                 "I2C2",
                                 "I2C3",
                                 "Infinity",
                                 "Int16Array",
                                 "Int32Array",
                                 "Int8Array",
                                 "InternalError",
                                 "JSON",
                                 "LOW",
                                 "LoopbackA",
                                 "LoopbackB",
                                 "Math",
                                 "Modules",
                                 "NaN",
                                 "Number",
                                 "OneWire",
                                 "Pin",
                                 "Promise",
                                 "ReferenceError",
                                 "RegExp",
                                 "SPI",
                                 "SPI1",
                                 "SPI2",
                                 "SPI3",
                                 "Serial",
                                 "Serial1",
                                 "Serial2",
                                 "Serial3",
                                 "Serial4",
                                 "Serial5",
                                 "Serial6",
                                 "Server",
                                 "Socket",
                                 "String",
                                 "SyntaxError",
                                 "Telnet",
                                 "TypeError",
                                 "USB",
                                 "Uint16Array",
                                 "Uint32Array",
                                 "Uint8Array",
                                 "Uint8ClampedArray",
                                 "Waveform",
                                 "analogRead",
                                 "analogWrite",
                                 "arguments",
                                 "atob",
                                 "btoa",
                                 "changeInterval",
                                 "clearInterval",
                                 "clearTimeout",
                                 "clearWatch",
                                 "decodeURIComponent",
                                 "dgramSocket",
                                 "digitalPulse",
                                 "digitalRead",
                                 "digitalWrite",
                                 "dump",
                                 "echo",
                                 "edit",
                                 "encodeURIComponent",
                                 "eval",
                                 "getPinMode",
                                 "getSerial",
                                 "getTime",
                                 "global",
                                 "httpCRq",
                                 "httpCRs",
                                 "httpSRq",
                                 "httpSRs",
                                 "httpSrv",
                                 "isFinite",
                                 "isNaN",
                                 "load",
                                 "parseFloat",
                                 "parseInt",
                                 "peek16",
                                 "peek32",
                                 "peek8",
                                 "pinMode",
                                 "poke16",
                                 "poke32",
                                 "poke8",
                                 "print",
                                 "process",
                                 "require",
                                 "reset",
                                 "save",
                                 "setBusyIndicator",
                                 "setInterval",
                                 "setSleepIndicator",
                                 "setTime",
                                 "setTimeout",
                                 "setWatch",
                                 "shiftOut",
                                 "trace",
                                 "url"};

const std::string methods[] = {"set",
                               "reduce",
                               "pop",
                               "replace",
                               "substring",
                               "substr",
                               "byteOffset",
                               "charCodeAt",
                               "apply",
                               "shift",
                               "find",
                               "fill",
                               "byteLength",
                               "startsWith",
                               "findIndex",
                               "slice",
                               "replaceWithconstructor",
                               "endsWith",
                               "write",
                               "buffer",
                               "call",
                               "split",
                               "trimconstructor",
                               "toString",
                               "match",
                               "writeAtTimeconstructor",
                               "sort",
                               "map",
                               "getMode",
                               "replaceWith",
                               "lastIndexOf",
                               "charAt",
                               "indexOf",
                               "some",
                               "sortconstructor",
                               "includes",
                               "every",
                               "forEach",
                               "splice",
                               "concat",
                               "toLowerCase",
                               "reset",
                               "unshiftconstructor",
                               "join",
                               "reverse",
                               "getInfo",
                               "read",
                               "bind",
                               "toggle",
                               "toUpperCase",
                               "toFixedconstructor",
                               "filter",
                               "length",
                               "mode",
                               "constructor",
                               "push",
                               "byteLengthconstructor"};
#endif  // if FUZZ_ESPURINO == 1

}  // namespace builtins

#endif  // ifndef BUILTINS_H_
