#ifndef BUILTINS_H_
#define BUILTINS_H_
#include <string>
namespace builtins {

const std::string variables[] = {
    "NaN",         "undefined",   "Reflect",     "Math",      "JSON",
    "Intl",        "WebAssembly", "WScript",     "console",   "variables",
    "functions",   "methods",     "top",         "__proto__", "E",
    "LN10",        "LN2",         "LOG2E",       "LOG10E",    "PI",
    "SQRT1_2",     "SQRT2",       "Platform",    "Arguments", "ARCH",
    "BUILD_TYPE",  "LINK_TYPE",   "BINARY_PATH", "OS",        "INTL_LIBRARY",
    "ICU_VERSION", "length",      "size"};

const std::string functions[] = {"eval",
                                 "parseInt",
                                 "parseFloat",
                                 "isNaN",
                                 "isFinite",
                                 "decodeURI",
                                 "decodeURIComponent",
                                 "encodeURI",
                                 "encodeURIComponent",
                                 "escape",
                                 "unescape",
                                 "Object",
                                 "Array",
                                 "Boolean",
                                 "Symbol",
                                 "Proxy",
                                 "Promise",
                                 "Date",
                                 "Function",
                                 "Number",
                                 "String",
                                 "RegExp",
                                 "ArrayBuffer",
                                 "DataView",
                                 "Int8Array",
                                 "Uint8Array",
                                 "Uint8ClampedArray",
                                 "Int16Array",
                                 "Uint16Array",
                                 "Int32Array",
                                 "Uint32Array",
                                 "Float32Array",
                                 "Float64Array",
                                 "Map",
                                 "Set",
                                 "WeakMap",
                                 "WeakSet",
                                 "Error",
                                 "EvalError",
                                 "RangeError",
                                 "ReferenceError",
                                 "SyntaxError",
                                 "TypeError",
                                 "URIError",
                                 "print",
                                 "read",
                                 "readbuffer",
                                 "readline",
                                 "extractBuiltins"};

const std::string methods[] = {"defineProperty",
                               "deleteProperty",
                               "get",
                               "getOwnPropertyDescriptor",
                               "getPrototypeOf",
                               "has",
                               "isExtensible",
                               "ownKeys",
                               "preventExtensions",
                               "set",
                               "setPrototypeOf",
                               "apply",
                               "construct",
                               "constructor",
                               "hasOwnProperty",
                               "propertyIsEnumerable",
                               "isPrototypeOf",
                               "toLocaleString",
                               "toString",
                               "valueOf",
                               "__defineGetter__",
                               "__defineSetter__",
                               "__lookupGetter__",
                               "__lookupSetter__",
                               "abs",
                               "acos",
                               "asin",
                               "atan",
                               "atan2",
                               "cos",
                               "ceil",
                               "exp",
                               "floor",
                               "log",
                               "pow",
                               "random",
                               "round",
                               "sin",
                               "sqrt",
                               "tan",
                               "imul",
                               "fround",
                               "log10",
                               "log2",
                               "log1p",
                               "expm1",
                               "cosh",
                               "sinh",
                               "tanh",
                               "acosh",
                               "asinh",
                               "atanh",
                               "hypot",
                               "trunc",
                               "sign",
                               "cbrt",
                               "clz32",
                               "min",
                               "max",
                               "stringify",
                               "parse",
                               "getCanonicalLocales",
                               "Collator",
                               "NumberFormat",
                               "DateTimeFormat",
                               "PluralRules",
                               "compile",
                               "compileStreaming",
                               "validate",
                               "instantiate",
                               "instantiateStreaming",
                               "Module",
                               "Instance",
                               "CompileError",
                               "RuntimeError",
                               "LinkError",
                               "Memory",
                               "Table",
                               "Echo",
                               "Quit",
                               "LoadScriptFile",
                               "LoadScript",
                               "LoadModule",
                               "SetTimeout",
                               "ClearTimeout",
                               "Attach",
                               "Detach",
                               "DumpFunctionPosition",
                               "RequestAsyncBreak",
                               "LoadBinaryFile",
                               "LoadTextFile",
                               "Flag",
                               "RegisterModuleSource",
                               "GetModuleNamespace",
                               "GetProxyProperties",
                               "Edit",
                               "push",
                               "concat",
                               "join",
                               "pop",
                               "reverse",
                               "shift",
                               "slice",
                               "splice",
                               "unshift",
                               "lastIndexOf",
                               "map",
                               "reduceRight",
                               "find",
                               "findIndex",
                               "fill",
                               "copyWithin",
                               "keys",
                               "values",
                               "entries",
                               "indexOf",
                               "sort",
                               "filter",
                               "flat",
                               "flatMap",
                               "forEach",
                               "some",
                               "every",
                               "includes",
                               "reduce",
                               "add",
                               "clear",
                               "delete"};
};      // namespace builtins
#endif  // ifndef BUILTINS_H_
